"""Polytope templates and random rotations.

Vertex generators (orthoplex, simplex, cube) plus Haar-random rotations. Probe
points are generated by ``_compiled.compute_probe_points`` on the live path.
"""

import math
from typing import Callable, Dict, Optional

import torch

from .solvers._shared import thin_qr


def get_orthoplex_vertices(
    dim: int,
    *,
    device: Optional[torch.device] = None,
    dtype: Optional[torch.dtype] = None,
    radius: float = 1.0,
    **kwargs,
) -> torch.Tensor:
    """``(2*dim, dim)``: the positive then negative unit vector along each axis."""
    eye = torch.eye(dim, dtype=dtype, device=device)
    points = torch.cat([eye, -eye], dim=0)
    return points * radius


def get_simplex_vertices(
    dim: int,
    *,
    device: Optional[torch.device] = None,
    dtype: Optional[torch.dtype] = None,
    radius: float = 1.0,
    **kwargs,
) -> torch.Tensor:
    """``(dim+1, dim)``: a regular simplex centered at the origin."""
    points = math.sqrt(1 + 1 / dim) * torch.eye(dim, dtype=dtype, device=device)
    points = points - ((math.sqrt(dim + 1) + 1) / math.sqrt(dim**3))

    last_vertex = (1 / math.sqrt(dim)) * torch.ones(1, dim, dtype=dtype, device=device)
    points = torch.cat([points, last_vertex], dim=0)

    # Centred and unit-norm by construction: the centroid measures ~2e-8 in the
    # default fp32 (exactly 0 in fp64).
    return points * radius


def get_cube_vertices(
    dim: int,
    *,
    device: Optional[torch.device] = None,
    dtype: Optional[torch.dtype] = None,
    radius: float = 1.0,
    **kwargs,
) -> torch.Tensor:
    """``(2**dim, dim)``: every sign combination, normalized by ``sqrt(dim)``."""
    n_vertices = 2**dim

    indices = torch.arange(n_vertices, dtype=torch.int64, device=device).unsqueeze(1)
    shifts = torch.arange(dim, dtype=torch.int64, device=device).unsqueeze(0)

    bits = (indices >> shifts) & 1
    # Resolve dtype for the float conversion (default to float32 if None)
    float_dtype = dtype if dtype is not None else torch.float32
    signs = 1.0 - 2.0 * bits.to(float_dtype)

    points = signs / math.sqrt(dim)
    return points * radius


POLYTOPE_MAP: Dict[str, Callable] = {
    "cube": get_cube_vertices,
    "orthoplex": get_orthoplex_vertices,
    "simplex": get_simplex_vertices,
}


# Widest batch where one batched QR still beat the reflection loop, indexed by is_cuda.
# Measured fp32 at dim 4, 8 and 16; each entry is the last batch QR won at every dim.
# Crossover table in docs/performance.md.
_QR_MAX_BATCH = {False: 256, True: 16}


def get_rotation_matrix_2d(theta: torch.Tensor) -> torch.Tensor:
    """``(...)`` angles to ``(..., 2, 2)`` rotation matrices."""
    c = torch.cos(theta)
    s = torch.sin(theta)
    row1 = torch.stack([c, -s], dim=-1)
    row2 = torch.stack([s, c], dim=-1)
    return torch.stack([row1, row2], dim=-2)


def get_random_rotation_matrices(
    batch: int,
    dim: int,
    device: Optional[torch.device] = None,
    dtype: Optional[torch.dtype] = None,
    generator: Optional[torch.Generator] = None,
) -> torch.Tensor:
    """Generate batched uniformly random rotation matrices on SO(dim).

    ``dim == 2`` uses the analytical uniform angle. Above that, the
    Diaconis-Shahshahani subgroup algorithm: ``Q = H_dim ... H_2 S``, each ``H_k``
    the Householder reflection taking ``e_1`` to a uniform point of ``S^(k-1)`` in
    the trailing ``k`` coordinates. Haar on ``O(dim)``; each reflection has
    ``det = -1``, so fixing ``S = (-1)^(dim-1)`` gives Haar on ``SO(dim)``.

    Batched reflections instead of ``torch.linalg.qr`` because cuSOLVER's batched geqrf
    is worst at exactly this shape, a wide batch of tiny matrices. Costs half a digit of
    orthonormality (1.2e-6 against 2.4e-7 in FP32).

    That inverts at small batch: the reflections cost ``dim - 1`` sequential launches
    whatever the batch, so at or below ``_QR_MAX_BATCH`` one batched QR draws the same
    Haar sample for less. Both are seeded, but they consume the stream differently, so a
    seeded run either side of the threshold is not comparable.

    Ref: Diaconis and Shahshahani, Prob. Eng. Inf. Sci. 1, 1987. Mezzadri,
    Notices AMS 54, 2007 (the QR sign fix).

    Args:
        batch: Number of rotation matrices to generate.
        dim: Dimension of each rotation matrix.
        device: Target device.
        dtype: Target dtype.
        generator: Optional torch.Generator for reproducibility.

    Returns:
        Rotation matrices of shape (batch, dim, dim) with det(R) = +1.
    """
    # Build in FP32 and cast back: half precision loses the rank-1 updates.
    resolved_dtype = dtype if dtype is not None else torch.float32
    compute_dtype = torch.float32 if resolved_dtype in (torch.bfloat16, torch.float16) else resolved_dtype

    # Sampling needs the generator's device to match the tensor's.
    sample_device = generator.device if generator is not None else device

    if dim == 2:
        angles = torch.empty(batch, device=sample_device, dtype=compute_dtype)
        angles.uniform_(0, 2 * math.pi, generator=generator)
        return get_rotation_matrix_2d(angles).to(device=device, dtype=dtype)

    # The QR runs where the sample is drawn, which is the generator's device when one is
    # given, not the requested output device.
    work_device = sample_device if sample_device is not None else torch.device("cpu")
    if batch <= _QR_MAX_BATCH[work_device.type == "cuda"]:
        # One thread for the whole branch on CPU, not just the factorization: LAPACK
        # spreads a batch of tiny QRs and the batched det over every core and the
        # synchronization dominates both. See docs/performance.md.
        prev_threads = torch.get_num_threads() if work_device.type == "cpu" else 1
        if prev_threads != 1:
            torch.set_num_threads(1)
        try:
            A = torch.randn(batch, dim, dim, device=sample_device, dtype=compute_dtype, generator=generator)
            Q, R = thin_qr(A)
            # Q diag(sign(diag R)) is Haar on O(dim). A zero pivot has measure zero but
            # would zero a column, so it maps to +1.
            diag = torch.diagonal(R, dim1=-2, dim2=-1)
            signs = torch.where(diag == 0, torch.ones_like(diag), diag.sign())
            # Negating one column on the det = -1 half is a measure-preserving bijection
            # onto SO(dim). det(Q diag(s)) = det(Q) prod(s) folds it into the same
            # multiply, so no second pass and no host sync.
            parity = (torch.linalg.det(Q) * signs.prod(dim=-1)).sign()
            signs = torch.cat([signs[:, :1] * parity.unsqueeze(-1), signs[:, 1:]], dim=-1)
            return (Q * signs.unsqueeze(-2)).to(device=device, dtype=dtype)
        finally:
            if prev_threads != 1:
                torch.set_num_threads(prev_threads)

    Q = torch.eye(dim, device=sample_device, dtype=compute_dtype).expand(batch, dim, dim).contiguous()
    # Fixed sign flip, not random: makes det(Q) = +1 without a batched torch.det.
    if dim % 2 == 0:
        Q[:, dim - 1, dim - 1] = -1.0

    for k in range(2, dim + 1):
        u = torch.randn(batch, k, device=sample_device, dtype=compute_dtype, generator=generator)
        u = u / torch.linalg.vector_norm(u, dim=-1, keepdim=True).clamp(min=1e-30)

        w = -u
        w[:, 0] += 1.0
        wsq = (w * w).sum(dim=-1, keepdim=True)
        # Degenerate only at u == e_1 exactly. Fall back to w = e_1, not to H = I,
        # which would flip det and break the fixed sign above. On CUDA the guard runs
        # unconditionally: reading `.any()` costs a host sync per loop iteration, so
        # dim-1 per step. On CPU the read is free and skipping the writes is cheaper.
        degenerate = wsq < 1e-12
        if not (Q.is_cuda or degenerate.any()):
            rows = Q[:, dim - k :, :]
            rows -= (2.0 / wsq).unsqueeze(-1) * w.unsqueeze(-1) * (w.unsqueeze(1) @ rows)
            continue
        w = torch.where(degenerate, torch.zeros_like(w), w)
        w[:, 0] = torch.where(degenerate[:, 0], torch.ones_like(w[:, 0]), w[:, 0])
        wsq = torch.where(degenerate, torch.ones_like(wsq), wsq)

        # Q <- H_k Q, trailing k rows only.
        rows = Q[:, dim - k :, :]
        rows -= (2.0 / wsq).unsqueeze(-1) * w.unsqueeze(-1) * (w.unsqueeze(1) @ rows)

    return Q.to(device=device, dtype=dtype)


def apply_biased_rotation(rot_mats: torch.Tensor, bias_dir: torch.Tensor) -> torch.Tensor:
    """Bias the first rotation axis toward ``bias_dir`` and re-orthonormalize.

    Replaces column 0 with the normalized bias direction, re-orthonormalizes the
    remaining columns against it, and flips the last column where needed so det = +1.
    Particles whose direction is too short to carry a heading keep their unbiased
    rotation.

    Uses modified Gram-Schmidt, not ``torch.linalg.qr``. Both give the same basis, but
    cuSOLVER's batched QR is far slower at the small ``dim`` and wide batch this sees,
    where Gram-Schmidt is accurate enough.

    Runs in fp32 for half-precision inputs and casts back. In bf16 the Gram matrix
    lands ~5.7e-3 off identity, past the orthonormality tolerance below, so every
    particle would fall back to its unbiased rotation and the bias would be dropped
    with no diagnostic.

    Args:
        rot_mats: Rotation matrices of shape (batch, dim, dim).
        bias_dir: Bias directions of shape (batch, dim), any magnitude.

    Returns:
        Biased rotation matrices of shape (batch, dim, dim), det = +1.
    """
    dim = rot_mats.shape[-1]
    if dim == 1:
        # SO(1) = {[[1]]}: a sign flip is a reflection, so the bias is not
        # representable. Return identity.
        return torch.ones_like(rot_mats)

    out_dtype = rot_mats.dtype
    if out_dtype in (torch.bfloat16, torch.float16):
        rot_mats = rot_mats.float()
        bias_dir = bias_dir.float()

    # Normalize here rather than at each call site: column 0 must be unit or the
    # Gram-Schmidt below orthogonalizes the rest against a scaled axis and returns a
    # non-orthonormal frame. Clamping the divisor instead of zeroing would do exactly
    # that, turning a 1e-12 direction into a column of norm 1e-2. Zeroing routes those
    # particles to the ``bias_ok`` fallback below.
    norms = torch.linalg.vector_norm(bias_dir, dim=-1, keepdim=True)
    bias_dir_norm = torch.where(norms > 1e-8, bias_dir / norms.clamp(min=1e-10), torch.zeros_like(bias_dir))

    out = rot_mats.clone()
    out[:, :, 0] = bias_dir_norm
    for col in range(1, dim):
        v = out[:, :, col].clone()
        # Two sweeps: one pass loses orthogonality when a column is nearly in the span
        # of the earlier ones (Q^T Q off by >1e-4 at dim=8). Twice is enough.
        for _ in range(2):
            for prev in range(col):
                proj = (v * out[:, :, prev]).sum(dim=-1, keepdim=True)
                v = v - proj * out[:, :, prev]
        raw_norm = torch.norm(v, dim=-1, keepdim=True)
        # A collapsed column carries no direction; keep the original instead of a zero.
        keep = raw_norm > 1e-6
        out[:, :, col] = torch.where(keep, v / raw_norm.clamp(min=1e-10), rot_mats[:, :, col])

    # A zero or non-finite bias leaves column 0 degenerate, so +e0 and -e0 would
    # coincide. Fall back to the unbiased rotation.
    bias_ok = torch.isfinite(bias_dir_norm).all(dim=-1) & (bias_dir_norm.abs().amax(dim=-1) > 0)
    # Orthonormality, not just finiteness. The collapse fallback above restores the
    # original column, which is in general not orthogonal to the ones already placed:
    # R = I, bias = e1 gives both columns equal to e1, a finite singular frame whose
    # duplicate probe directions would still be used. Checking the Gram matrix is one
    # small (pdim, pdim) matmul and catches every such case.
    gram = out.transpose(-2, -1) @ out
    eye = torch.eye(dim, device=out.device, dtype=out.dtype)
    orthonormal = (gram - eye).abs().amax(dim=-1).amax(dim=-1) < 1e-3
    valid = torch.isfinite(out).all(dim=-1).all(dim=-1) & bias_ok & orthonormal  # (batch,)
    out = torch.where(valid[:, None, None], out, rot_mats)

    # Flip the last column for det = +1.
    flip = (torch.det(out) < 0).unsqueeze(-1)
    out[:, :, -1] = torch.where(flip, -out[:, :, -1], out[:, :, -1])
    return out.to(out_dtype)
